/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39

  Company:
      Microchip Technology, Inc.
 
  File Name:
     new_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif


/*****************************************************************************
 * SECTION: IPU Buffer Size Check
 *****************************************************************************/
#if (GFX_COMPRESSED_BUFFER_SIZE < 4132)
#warning The GFX_COMPRESSED_BUFFER_SIZE defined in hardware profile is smaller than the compressed size of the IPU resources.
#endif

#if (GFX_DECOMPRESSED_BUFFER_SIZE < 38028)
#warning The GFX_DECOMPRESSED_BUFFER_SIZE defined in hardware profile is smaller than the decompressed size of the IPU resources.
#endif

/*****************************************************************************
 * SECTION: External Memory Font Raster Buffer Size Check
 *****************************************************************************/
#if (GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE < 500)
#error The GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE defined in GraphicsConfig header file is smaller than the require size needed to support these external fonts.
#error Please define "#define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE (500)" in GraphicsConfig.h.
#endif

#if (GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE > 500)
#warning The GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE defined in GraphicsConfig header file is larger than is needed for these external fonts.
#endif


/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_EXTERNAL_DISABLE
#error The GFX_CONFIG_IMAGE_EXTERNAL_DISABLE is defined in system_config.h header file.
#endif

#ifdef GFX_CONFIG_IPU_DECODE_DISABLE
#error The GFX_CONFIG_IPU_DECODE_DISABLE is defined in system_config.h header file.
#endif

/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_EXTERNAL_DISABLE
#error The GFX_CONFIG_FONT_EXTERNAL_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: Wait_temp
 * Description:  30x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait_temp =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00000000 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 30,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 143,
    .resource.image.parameter2.rawSize = 1416,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Intro
 * Description:  226x166 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Intro =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00000090 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 226,
    .resource.image.height = 166,
    .resource.image.parameter1.compressedSize = 2076,
    .resource.image.parameter2.rawSize = 38032,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Param_btn
 * Description:  224x26 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Param_btn =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000008B0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 224,
    .resource.image.height = 26,
    .resource.image.parameter1.compressedSize = 81,
    .resource.image.parameter2.rawSize = 6340,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait1
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait1 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00000910 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 668,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait2
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait2 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00000BB0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 696,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait3
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait3 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00000E70 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 668,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait4
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait4 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001110 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 687,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Param_btn_press
 * Description:  224x26 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Param_btn_press =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000013C0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 224,
    .resource.image.height = 26,
    .resource.image.parameter1.compressedSize = 80,
    .resource.image.parameter2.rawSize = 6340,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Larrow_press
 * Description:  55x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Larrow_press =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001410 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 55,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 382,
    .resource.image.parameter2.rawSize = 2164,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Rarrow_press
 * Description:  55x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Rarrow_press =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001590 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 55,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 376,
    .resource.image.parameter2.rawSize = 2164,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Larrow
 * Description:  55x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Larrow =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001710 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 55,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 276,
    .resource.image.parameter2.rawSize = 2164,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Rarrow
 * Description:  55x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Rarrow =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001830 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 55,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 273,
    .resource.image.parameter2.rawSize = 2164,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_Adrenaline
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_Adrenaline =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001950 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 378,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_Midazolam
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_Midazolam =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001AD0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 442,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_Morph_Midaz
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_Morph_Midaz =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001C90 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 473,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_NoName
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_NoName =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001E70 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 332,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_Noradrenaline
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_Noradrenaline =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00001FC0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 886,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: drug_Remitentanil
 * Description:  102x54 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR drug_Remitentanil =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00002340 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 102,
    .resource.image.height = 54,
    .resource.image.parameter1.compressedSize = 353,
    .resource.image.parameter2.rawSize = 6024,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait5
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait5 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000024B0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 658,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait6
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait6 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00002750 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 707,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait7
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait7 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00002A20 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 668,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Wait8
 * Description:  28x28 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Wait8 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00002CC0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 28,
    .resource.image.height = 28,
    .resource.image.parameter1.compressedSize = 694,
    .resource.image.parameter2.rawSize = 1300,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_ContROV
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_ContROV =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00002F80 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 1110,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_ContVOT
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_ContVOT =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000033E0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 1176,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_IntROV
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_IntROV =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00003880 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 988,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_IntVOT
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_IntVOT =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00003C60 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 985,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_PCA
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_PCA =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00004040 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 551,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: prog_Step
 * Description:  110x72 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR prog_Step =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00004270 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 110,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 525,
    .resource.image.parameter2.rawSize = 8436,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: clock_img
 * Description:  128x128 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR clock_img =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00004480 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 128,
    .resource.image.height = 128,
    .resource.image.parameter1.compressedSize = 4131,
    .resource.image.parameter2.rawSize = 16900,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Pointer_img
 * Description:  12x12 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Pointer_img =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000054B0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 12,
    .resource.image.height = 12,
    .resource.image.parameter1.compressedSize = 128,
    .resource.image.parameter2.rawSize = 660,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Pressbar_img
 * Description:  33x199 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Pressbar_img =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005530 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 33,
    .resource.image.height = 199,
    .resource.image.parameter1.compressedSize = 110,
    .resource.image.parameter2.rawSize = 7080,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: NoLimit
 * Description:  50x31 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR NoLimit =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000055A0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 50,
    .resource.image.height = 31,
    .resource.image.parameter1.compressedSize = 292,
    .resource.image.parameter2.rawSize = 2064,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: NoLimit_press
 * Description:  50x31 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR NoLimit_press =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000056D0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 50,
    .resource.image.height = 31,
    .resource.image.parameter1.compressedSize = 251,
    .resource.image.parameter2.rawSize = 2064,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat8
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat8 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000057D0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 324,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat1
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat1 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005920 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 366,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat10
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat10 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005A90 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 284,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat2
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat2 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005BB0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 399,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat3
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat3 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005D40 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 384,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat4
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat4 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00005EC0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 378,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat5
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat5 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006040 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 370,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat6
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat6 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000061C0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 349,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat7
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat7 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006320 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 326,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Bat9
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Bat9 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006470 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 356,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: setting
 * Description:  29x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR setting =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000065E0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 29,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 1380,
    .resource.image.parameter2.rawSize = 1384,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Speaker0
 * Description:  36x36 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Speaker0 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006B50 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 36,
    .resource.image.height = 36,
    .resource.image.parameter1.compressedSize = 478,
    .resource.image.parameter2.rawSize = 1812,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Speaker1
 * Description:  36x36 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Speaker1 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006D30 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 36,
    .resource.image.height = 36,
    .resource.image.parameter1.compressedSize = 676,
    .resource.image.parameter2.rawSize = 1812,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Speaker2
 * Description:  36x36 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR Speaker2 =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00006FE0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 36,
    .resource.image.height = 36,
    .resource.image.parameter1.compressedSize = 899,
    .resource.image.parameter2.rawSize = 1812,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: BatAC
 * Description:  24x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR BatAC =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00007370 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 24,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 477,
    .resource.image.parameter2.rawSize = 1236,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: BBat_img
 * Description:  33x123 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR BBat_img =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x00007550 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 33,
    .resource.image.height = 123,
    .resource.image.parameter1.compressedSize = 66,
    .resource.image.parameter2.rawSize = 4572,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: BBat1_img
 * Description:  33x123 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR BBat1_img =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000075A0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 33,
    .resource.image.height = 123,
    .resource.image.parameter1.compressedSize = 66,
    .resource.image.parameter2.rawSize = 4572,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: KVO
 * Description:  40x30 pixels, 8-bits per pixel
 ***********************************/
const GFX_RESOURCE_HDR KVO =
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_IPU),
    .ID = 2,
    .resource.image.location.edsAddress = (__eds__ char *) (0x000075F0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.image.width = 40,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 281,
    .resource.image.parameter2.rawSize = 1716,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_Bold_18
 * Description:  Height: 21 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_Bold_18 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x00007710 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x0015,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_26
 * Description:  Height: 31 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_26 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x00008430 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x001F,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_24
 * Description:  Height: 29 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_24 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x00009A70 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x001D,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_Bold_28
 * Description:  Height: 33 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_Bold_28 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x0000AEE0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x0021,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_14
 * Description:  Height: 17 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_14 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x0000C880 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x0011,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_Bold_72
 * Description:  Height: 84 pixels, 1 bit per pixel, Range: '.' to ':'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_Bold_72 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x0000D0E0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x002E,
    .resource.font.header.lastChar = 0x003A,
    .resource.font.header.height = 0x0054,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_36
 * Description:  Height: 42 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_36 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x0000E3D0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007E,
    .resource.font.header.height = 0x002A,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_86
 * Description:  Height: 100 pixels, 1 bit per pixel, Range: '.' to ':'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_86 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x00010850 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x002E,
    .resource.font.header.lastChar = 0x003A,
    .resource.font.header.height = 0x0064,
};
/*********************************
 * Installed Font Structure
 * Label: Arial_Narrow_Bold_86
 * Description:  Height: 100 pixels, 1 bit per pixel, Range: '.' to ':'
 ***********************************/
const GFX_RESOURCE_HDR Arial_Narrow_Bold_86 = 
{
    .type = (GFX_RESOURCE_MEMORY_EDS_EPMP | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0002,
    .resource.font.location.edsAddress = (__eds__ char *) (0x00011FA0 + GFX_EPMP_CS2_BASE_ADDRESS),
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x002E,
    .resource.font.header.lastChar = 0x003A,
    .resource.font.header.height = 0x0064,
};
